version: '3'

services:
  terabox-bot:
    build: .
    container_name: terabox-bot
    restart: always
    environment:
      - TELEGRAM_API=${TELEGRAM_API}
      - TELEGRAM_HASH=${TELEGRAM_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - DUMP_CHAT_ID=${DUMP_CHAT_ID}
      - FSUB_ID=${FSUB_ID}
      - REQUEST_CHAT_ID=${REQUEST_CHAT_ID}
      - USER_SESSION_STRING=${USER_SESSION_STRING}
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./config.env:/app/config.env
      - ./thumbnails:/app/thumbnails
